project:
  name: Skin Lesion Few-Shot Classification
  author: nousin nihal
  description: Few-Shot Learning for Rare Skin Lesions using Prototypical Networks

data:
  train_path: data/ISIC2019/train
  val_path: data/ISIC2019/val
  test_path: data/ISIC2019/test
  image_size: 224
  augment:
    horizontal_flip: true
    vertical_flip: true
    brightness_contrast: true
    shift_scale_rotate: true
    blur: true
    noise: true
    cutout: true
    random_crop: false
    coarse_dropout: false
    elastic_transform: false
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]

fewshot:
  n_way: 5
  k_shot: 5
  query: 15

train:
  episodes: 1000
  batch_size: 16
  lr: 0.0005
  patience: 20
  val_interval: 25
  num_workers: 4
  checkpoint_dir: models/checkpoints
  log_dir: results/logs

test:
  checkpoint_path: models/checkpoints/protonet_best.pth
  save_predictions: false  # set true if saving CSVs
  prediction_path: results/predictions.csv

demo:
  classes_path: demo/sample_classes  # for gradio demo mode
  output_dir: results/demo_outputs
  model_checkpoint: models/checkpoints/protonet_best.pth

inference:
  use_gpu: true
  confidence_threshold: 0.5
