# Configuration for Few-Shot Skin Lesion Classification
experiment_name: "protonet_skinlesion_fewshot"

device: "cuda"  # or "cpu"

seed: 42

dataset:
  name: "ISIC2019"
  root_dir: "data/"
  image_size: 224
  augmentations: true
  normalize: true

few_shot:
  n_way: 5
  k_shot: 5
  query_per_class: 5
  val_episodes: 100
  test_episodes: 200

training:
  epochs: 100
  batch_size: 1  # one episode per batch
  optimizer: "Adam"
  learning_rate: 1e-3
  weight_decay: 1e-5
  scheduler: "StepLR"
  step_size: 20
  gamma: 0.5
  early_stopping_patience: 15

model:
  type: "ProtoNet"
  backbone: "resnet18"
  pretrained: true
  embedding_dim: 512

logging:
  log_dir: "results/logs/"
  tensorboard: true
  log_frequency: 10
  save_best_only: true

checkpoint:
  save_dir: "models/"
  save_name: "protonet_best.pth"
  resume_from: null  # or "models/protonet_last.pth"
