# config/config.yaml

# Experiment Settings
experiment:
  name: "fewshot_skin_lesion"
  seed: 42
  device: "cuda"  # or "cpu"

# Few-Shot Settings
fewshot:
  n_way: 5        # Number of classes per episode
  k_shot: 5       # Number of support samples per class
  n_query: 15     # Number of query samples per class
  n_episodes: 100 # Episodes per epoch

# Dataset Settings
dataset:
  name: "ISIC2019"
  data_path: "data/"
  splits_path: "splits/"
  input_size: 224

# Training Settings
train:
  epochs: 50
  batch_size: 1
  lr: 0.001
  weight_decay: 0.0001
  save_path: "models/proto_model.pth"
  log_path: "results/train_logs.csv"

# Testing / Inference
test:
  checkpoint: "models/proto_model.pth"
  save_results: "results/test_results.csv"

# Demo
demo:
  sample_image: "demo_images/sample.jpg"
